name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?palette=github
            github-contribution-grid-snake-dark.svg?palette=github-dark
            github-contribution-grid-snake-custom.svg?color_snake=#00FF00&color_dots=#444B5A,#3C4453,#2F3944,#212936,#0C1117

      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
